### ISSUE TITLE
[Sensor] The distance sensor does not prevent accidental touch during phone calls

### ISSUE THREAD

**Issue by stuartore** [stuartore/device_xiaomi_psyche#5]
As title.

**Comment by stuartore** [comment]
有可能这个设备没有接近传感器，而是光传感器和陀螺仪。MIUI可能通过判断光亮度值0和陀螺仪达到防误触目的
> Issue关闭

Add: This device has a proximity sensor.
> Referrence: https://github.com/VoidUI-Devices/kernel_xiaomi_sm8250/commit/b201d18e3a991b6d9ff42a69cc441c9706efdfc2

**Comment by stuartore** [comment]
This issue maybe related to Ultra sound proximity sensor by refferring  https://github.com/Tkiliay/device_xiaomi_alioth/commit/c6b24481dd4c24f600ec46e227bfbf459a92ad1c

**Comment by stuartore** [comment]
Another refferrence: https://github.com/Tkiliay/device_xiaomi_alioth/commit/db7c269f60f858e5d2a5a8162c6c8dbe12b7e0ee

**Comment by stuartore** [comment]
missing [audio_platform_info_intcodec.xml](https://github.com/Xtended-Devices/android_device_xiaomi_alioth/blob/6b4b14db36e988dbceaf321b660fd5e10021ec73/audio/audio_platform_info_intcodec.xml#L189) 
+ Another refferrence: https://github.com/Chaitanyakm/device_xiaomi_alioth/commit/ba9b6b43c6dc1eb92cdba0f280e93377755932fd

**Comment by stuartore** [comment]
Since above commit causes screen flickering repeatedly I reverted it.

**Comment by stuartore** [comment]
Fix ultrasound sensor first, then config in overlay to enable block accidently touch on calling  feature.

**Comment by Moonlight4004** [comment]
Drop sensors.elliptic.so from hals.conf to fix proximity. That lib is unsupported and try to load not existing physical proximity while we have virtual one.

**Comment by stuartore** [comment]
> Drop sensors.elliptic.so from hals.conf to fix proximity. That lib is unsupported and try to load not existing physical proximity while we have virtual one.

Thanks.  I was going for my work this month. I'll fix it as you say.
